### ISSUE TITLE
Getting an active maintainer for the project

### ISSUE THREAD

**Issue by mattock** [freight-team/freight#111]
@freight-team/developers I see that there are lots of PRs open and I don't see much activity in getting them merged.

I currently maintain only one freight-based apt repository which works for my use-case. So I don't want to commit myself to managing this project.

What I would propose is adding @yegorich to the team - he's the most active contributor right now. 

What do you think?

**Comment by yegorich** [comment]
Let's move the project forward.

**Comment by mattock** [comment]
@yegorich you should have received an invite with write access. I can bump that up to admin access if needed.

**Comment by yegorich** [comment]
@mattock thanks for giving the write access. I have merged the test related PRs. The next would be to get GitHub actions running. Then we can take a look at the other open PRs.

**Comment by mattock** [comment]
No problem @yegorich! Good to see somebody maintaining the project actively. My role has mainly been maintaining the apt repo for freight itself.

**Comment by yegorich** [comment]
Now I do need the admin privileges to be able to add secrets to the repo. 

Btw there is still a demand for maintaining the apt repo, i.e. adding buster and so on.

**Comment by mattock** [comment]
You have write access now. I will add the buster repo.
