### ISSUE TITLE
no debian buster repo for installing freight from Debian archive

### ISSUE THREAD

**Issue by igagis** [freight-team/freight#112]
In the `README` there is a "Install from Debian archive" section:
https://github.com/freight-team/freight#from-a-debian-archive

but the debian repo does not contain `buster` distro:
http://build.openvpn.net/debian/freight_team/dists/

Though the `stretch` is there.

Need to add packages for `buster` distro.

**Comment by mattock** [comment]
I added the "buster" repo. In practice the package is exactly the same for every distro.
