### ISSUE TITLE
why packages from cache are not symlinked to packages from lib?

### ISSUE THREAD

**Issue by igagis** [freight-team/freight#113]
Currently, packages are added to the `libdir`. After `freight-cache` the `cachedir/pool` is populated with the packages from `libdir` by copying the packages there (or are those hard links?). In case the packages are copied, isn't it better to make package symlinks from `cachedir/pool` to `libdir`?

**Comment by ppoilbarbe** [comment]
Normally, it is hard links, so no space is wasted.
Type "ls -l" the number of links should be 3 of more. If the file were just copied, the number of links (second column in "ls -l") would have been 1.

**Comment by igagis** [comment]
Ok
