### ISSUE TITLE
tee: No such file or directory

### ISSUE THREAD

**Issue by minecraftchest1** [freight-team/freight#119]
When running `freight cache`, I get the following error:
`tee: /var/cache/freight/dists/squeeze-20210928183214582427228/main/binary-arm64/Packages: No such file or directory`. I verified that the file in question does indeed exist. If it makes a difference, I am running it as a standred user, but made sure that freight was able to write to its directories.

Edit: I found that it is creating the directories for AMD packages, but not arm.

**Comment by yegorich** [comment]
@minecraftchest1 

- What freight version are you using?
- Was there any earlier version that was working? 
- What is your Linux distribution, you run freight on?

**Comment by yegorich** [comment]
Could you also share your `freight.conf`? Or at least your `ARCHS` value?

**Comment by minecraftchest1** [comment]
I installed freight from master yesterday. This is my first time using freight. I am running Ubuntu mate 21.04 64 bit on Raspberry Pi 4.

I only have my gpg key email listed in the config file.

**Comment by yegorich** [comment]
Then you also need to specify `ARCHS=armhf` or whatever arch you are using.

**Comment by minecraftchest1** [comment]
I will do.



Sent from my T-Mobile 4G LTE Device



-------- Original message --------
From: Yegor Yefremov ***@***.***>
Date: 9/29/21 7:31 AM (GMT-06:00)
To: freight-team/freight ***@***.***>
Cc: Minecraftchest1 ***@***.***>, Mention ***@***.***>
Subject: Re: [freight-team/freight] tee: No such file or directory (#119)


Then you also need to specify ARCHS=armhf or whatever arch you are using.

**Comment by yegorich** [comment]
@minecraftchest1 can we close the issue?
