### ISSUE TITLE
unclear if freight is safe against parallel invocation

### ISSUE THREAD

**Issue by mhaberler** [freight-team/freight#31]
assume freight-cache is run concurrently - will things go haywire?

btw thanks for working on this - really worth it and very much appreciated!

**Comment by domcleal** [comment]
It's intended to be safe to run concurrently, as far as I know - we've always run it concurrently on theforeman.org, and it's not gone wrong yet to my knowledge.  It takes quite a bit of care to build all metadata into a temp directory and then flip symlinks.

**Comment by mhaberler** [comment]
thanks a lot - makes my job easier ;)

**Comment by josegonzalez** [comment]
This can probably be closed :)

**Comment by mmoll** [comment]
:smile:
