### ISSUE TITLE
freight-add: raising an error when adding an already existing file

### ISSUE THREAD

**Issue by ppoilbarbe** [freight-team/freight#37]
We have automatic tools to add and check repository managed by freight.
It would be nice to create (if wanted) an error (exit code not 0) when adding a file in repository (freight-add) which has already been added.

We already do this by checking the file and if it does not exist send an error to the asking user, but it is not atomic like the ln command in freight-add command.

Attached is a patch which can do this:

- By option _-e_ or _--add-error_
- By environment variable _FREIGHT_ADD_ERROR_ if defined not empty

[freight-error-add.patch](https://github.com/freight-team/freight/files/469590/freight-error-add.patch.txt)

**Comment by ppoilbarbe** [comment]
The patch was an old version (setting the env var empty will not authorise controlling the behaviour from outside the command).

[freight-error-add.patch](https://github.com/freight-team/freight/files/469628/freight-error-add.patch.txt)

**Comment by ppoilbarbe** [comment]
This was an old version of the patch if _FREIGHT_ADD_ERROR_ is set empty in script it cannot be controlled outside the command.

[freight-error-add.patch](https://github.com/freight-team/freight/files/469645/freight-error-add.patch.txt)

**Comment by domcleal** [comment]
Could you open a pull request with the suggested patch please? it's hard to review from an attachment. https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/ has more info.

**Comment by ppoilbarbe** [comment]
Ok. I'll see how to do this.
