### ISSUE TITLE
Minor suggestion from shellcheck linting of freight-init

### ISSUE THREAD

**Issue by brother** [freight-team/freight#42]
https://github.com/freight-team/freight/blob/master/bin/freight-init#L72 reads

`[ -z "$GPG" -o -z "$DIRNAME" ] && usage 1`

This should be changed to 

`[ -z "$GPG" ] || [ -z "$DIRNAME" ] && usage 1`

Example

```shell
$ [ -z "$GPG" ] || [ -z "$DIRNAME" ] && echo foo 
foo
$ GPG=1
$ [ -z "$GPG" ] || [ -z "$DIRNAME" ] && echo foo
foo
$ DIRNAME=1
$ [ -z "$GPG" ] || [ -z "$DIRNAME" ] && echo foo
$ [ -z "$GPG" ] && echo foo
$ [ -z "$DIRNAME" ] && echo foo
$ unset GPG
$ [ -z "$GPG" ] && echo foo
foo
$ [ -z "$GPG" ] || [ -z "$DIRNAME" ] && echo foo
foo
$ 
```

Used the online tool at http://shellcheck.net to do the linting of this file.

**Comment by mmoll** [comment]
Also applies to #43: I do use a newer shellcheck version on my workstation, but for the automatic tests only the version provided in Ubuntu/trusty is available. Unless there's a simple method to bring in a newer shellcheck into the tests, it's IMHO not needed to fix everything if there are no real problems seen application-wise. But please feel free to pull request your changes!

**Comment by brother** [comment]
You could fetch the shellcheck docker image and use that for execution ofc =)
