### ISSUE TITLE
Test suite required

### ISSUE THREAD

**Issue by domcleal** [freight-team/freight#5]
A test suite is required to help us prevent regressions, something that can easily be enabled with Travis CI on this repository.

As to frameworks, [bats](https://github.com/sstephenson/bats#readme) would be quite an easy way to write tests in the same language as the project.  It can be installed easily on Travis CI, and we just create a directory of .bats files containing individual tests to test different pieces of functionality.

**Comment by mattock** [comment]
@domcleal :+1: I have never used bats, but it looks straightforward enough.
