### ISSUE TITLE
Let use keyring.gpg or pubkey.gpg ?

### ISSUE THREAD

**Issue by narcisgarcia** [freight-team/freight#50]
At  README.md is documented to register Freight project's repository using repo-public.gpg , but it's indicated to people register new made repositories using keyring.gpg
Why the difference?

Can this be better for usage indication?
`wget -O - http://example.com/pubkey.gpg | sudo apt-key add -`

**Comment by mmoll** [comment]
@mattock could you have a look here? Although I think this needs no "fixing", as that documentation is about freight's repo, which is hosted by OpenVPN, where things might be different in general.

**Comment by mmoll** [comment]
I think this is fine as-is.
