### ISSUE TITLE
rcrowley/freight -> freight-team/freight

### ISSUE THREAD

**Issue by gvengel** [freight-team/freight#51]
Have you guys talked to @rcrowley about officially taking over the project? There are no pointers to freight-team from rcrowley, and all the Google results for freight point to his now inactive repository. I had to find this fork by tracing back @domcleal's commits in the Fedora package to his blog.

**Comment by mmoll** [comment]
There was no response ever in https://github.com/rcrowley/freight/issues/70 or in PRs over there, so I guess there's nothing we can so...
