### ISSUE TITLE
Releasing freight 0.3.11?

### ISSUE THREAD

**Issue by mattock** [freight-team/freight#58]
@mmoll , @domcleal : what about releasing freight 0.3.11 soon? If we merge PR
https://github.com/freight-team/freight/pull/57 then 0.3.11 would include these changes:
````
David R. Bild (2):
      Add NotAutomatic and ButAutomaticUpgrades to conf
      Include NotAutomatic and ButAutomaticUpgrades in Release files

Jeremy Teale (1):
      Prevent GPG >= 2.1 from using .kbx pubring format

Stephen Ryan (1):
      Let install-man task work on second and subsequent attempts

Vasily Laur (2):
      Debianize the sources
      Change instruction to build deb package in README
````

**Comment by domcleal** [comment]
Sure!

**Comment by mmoll** [comment]
@mattock I just merged #57 and bumped the version to 0.3.11, go for it! :shipit:

**Comment by mattock** [comment]
Ok, finally 0.3.11 is in our apt repository - sorry it took so long. Feel free to bug me as much as you need in the future :smile:.

I just issued PR https://github.com/freight-team/freight/pull/59 which is related to the release.

**Comment by mmoll** [comment]
#59 got merged and the release got tagged
