### ISSUE TITLE
Publish Debian package archive

### ISSUE THREAD

**Issue by domcleal** [freight-team/freight#6]
A new archive of packages should be provided for upcoming releases.

**Comment by mattock** [comment]
As discussed in PR https://github.com/freight-team/freight/pull/3 I can take care of this.

**Comment by mattock** [comment]
Fixed. Usage instructions for the new repository are in [README.md](https://github.com/freight-team/freight/blob/master/README.md). Version number of freight has been bumped to 0.3.6-2 to allow easy upgrades from rcrowley's 0.3.5.
