### ISSUE TITLE
Installation on Ubuntu18.04 fails

### ISSUE THREAD

**Issue by Dancho80** [freight-team/freight#85]
after running:
`sudo apt-get update`
got an error:
`The repository 'http://build.openvpn.net/debian/freight_team bionic Release' does not have a Release file.`
and after running:
`sudo apt-get -y install freight`
error:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package freight is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'freight' has no installation candidate

```

**Comment by mmoll** [comment]
@mattock I guess the repo needs the new distro added?

**Comment by Dancho80** [comment]
so could you add a "bionic" distribution to your repo please?

**Comment by mattock** [comment]
@Dancho80 you can use "xenial" for now. But yes, I will add the next release of freight (coming up soon) also to "bionic".

**Comment by mattock** [comment]
There's a "bionic" repository now. It includes the latest release (0.3.12) I made a few minutes ago.

**Comment by retorquere** [comment]
Same problem with cosmic. Can 18.10 be added?
