### ISSUE TITLE
InRelease.gpg is missing

### ISSUE THREAD

**Issue by Dancho80** [freight-team/freight#86]
When trying to use this commit: https://github.com/freight-team/freight/commit/0a8c99a761e08e1aac8fd702338afe75f6d892a7 
InRelease.gpg file is not created so when running: 
`sudo apt-get update`
we got an error:
`bionic InRelease: The following signatures couldn't be verified because the public key is not available:`

**Comment by mmoll** [comment]
AFAICT, that's fine http://archive.ubuntu.com/ubuntu/dists/bionic/ also doesn't have it. InRelease is the Releae file plus the GPG signature in one plaintest file.

**Comment by mmoll** [comment]
NTW, reading the message again, I think you miss the repo's key on the client.

**Comment by Dancho80** [comment]
Sorry, you were right. According to the:
https://wiki.debian.org/DebianRepository/Format
"...InRelease files are signed in-line while Release files should have an accompanying Release.gpg file."
