### ISSUE TITLE
Freight migration to another server

### ISSUE THREAD

**Issue by Dancho80** [freight-team/freight#89]
Do you have some kind of wiki/man for migrating a freight repo from one server to another? Just copy some folder(s)?

**Comment by mmoll** [comment]
Yes, rsync -aH or similar should do the job.

**Comment by Dancho80** [comment]
Thanks!
what folders should we move?
VARLIB or
VARCACHE
or both of them?

**Comment by mmoll** [comment]
VARLIB alone and rebuilding the repos would probably suffice, but if you have the opportunity to just sync both, that's easier anyway.

**Comment by mmoll** [comment]
@Dancho80 closing this issue, please reopen, if something isn't turning out as intended.
