### ISSUE TITLE
`find: command not found`, findutils missing dependency

### ISSUE THREAD

**Issue by mjsir911** [freight-team/freight#95]
In a minimal `fedora` docker container, I've run this
```
$ yum -y install freight
$ freight add my.deb apt/squeeze
$ freight cache
/usr/bin/freight-cache: line 95: find: command not found
```

`yum install findutils` fixes this issue

**Comment by mmoll** [comment]
@mjsir911 please file a bug over at the RPM source: https://apps.fedoraproject.org/packages/freight/bugs
